### PR TITLE
Fix syntax hiighlighting of code block

### PR DESCRIPTION
**Pull request by rugk**

### CODE REVIEW

**Review by elrido — DISMISSED** [review]
For consistency, could we apply the same to all shell examples? (not the k8s config, though)

**Comment by rugk** [comment]
The other ones already have `bash` highlighting (that likely looks the same).

**Comment by rugk** [comment]
Ah ok, $ was missing and I changed it to be consistent now,

**Review by elrido — APPROVED** [review]

**Comment by elrido** [comment]
Thank you, I've updated the https://hub.docker.com/r/privatebin/nginx-fpm-alpine page from it.

**Pull request merged**
