### PR TITLE
document/link to the GitHub container registry

### LINKED ISSUE #85: Push images to alternative registry (eg. Github Container Registry)
I would like to request that the Github Action to push images would be updated to also push to Github Container Registry, to bypass Docker Hub's pull limits.

https://developers.redhat.com/blog/2021/02/18/how-to-work-around-dockers-new-download-rate-limit-on-red-hat-openshift#:~:text=Docker%27s%20new%20rate%20limit,-Docker%20recently%20changed&text=The%20company%20now%20has%20a,from%20a%20single%20IP%20address.

### PR DESCRIPTION
**Pull request by elrido**
Concludes/closes #85 by documenting the links to the GitHub container registry.

Please do comment on the wording, grammar, etc.

### CODE REVIEW

**Comment by elrido** [comment]
@Zoey2936, I'd also appreciate your feedback on this.

**Comment by Zoey2936** [comment]
Maybe also note somewhere that to use ghcr it is required to use `ghcr.io/privatebin/nginx-fpm-alpine` instead of `privatebin/nginx-fpm-alpine`?

**Comment by elrido** [comment]
> Maybe also note somewhere that to use ghcr it is required to use `ghcr.io/privatebin/nginx-fpm-alpine` instead of `privatebin/nginx-fpm-alpine`?

Good idea, attempt to apply it in 433ac78. Do we need to explain why someone may want to use a different registry? (i.e. docker hub pull limits for anonymous users - though with our sponsored org account that should now be less of an issue)

**Comment by Zoey2936** [comment]
> > Maybe also note somewhere that to use ghcr it is required to use `ghcr.io/privatebin/nginx-fpm-alpine` instead of `privatebin/nginx-fpm-alpine`?
> 
> Good idea, attempt to apply it in [433ac78](https://github.com/PrivateBin/docker-nginx-fpm-alpine/commit/433ac78a2904693ae7adb08518d7e9faa21707e0). Do we need to explain why someone may want to use a different registry? (i.e. docker hub pull limits for anonymous users - though with our sponsored org account that should now be less of an issue)

I think not

**Pull request merged**
