### PR TITLE
Add stable tag on push

### LINKED ISSUE #125: Don't push every day to latest
It would be nice if the image gets only pushed if there are changes, at least to latest. It is very annoying to update my PrivateBin container every day and I don't see any reason to push the container daily, maybe to nightly or edge or something like this, no problem, but would it not be enough that latest get only pushed on a new release? Thanks!

### PR DESCRIPTION
**Pull request by Zoey2936**
Closes #125
I think should work, can you have a look please @elrido ?

### CODE REVIEW

**Review by elrido — APPROVED** [review]
Thank you, it looks good to me. After we merge it, I'd expect it to build the image including the new stable tag, but not yet push it, because it will have GITHUB_REF set to master, not a tag.

**Comment by Zoey2936** [comment]
Thanks!

**Comment by elrido** [comment]
It looks as expected, in the logs of the github action I can see this (for the PDO variant):
```
+ docker build --pull --no-cache --load --tag ***/pdo:latest --tag ***/pdo:master --tag ***/pdo:master --tag ***/pdo:stable --build-arg ALPINE_PACKAGES=php81-pdo_mysql,php81-pdo_pgsql --build-arg COMPOSER_PACKAGES= .
```
from https://github.com/PrivateBin/docker-nginx-fpm-alpine/actions/runs/3759625789

Now all that is left is pushing a tag to trigger the push of a new stable image. I'll see if I can find an opportunity to do that, soon, or otherwise re-tag some images manually.

**Comment by rugk** [comment]
I think this is a good idea. Maybe we should adjust the Readme to point to the new stable tag then?

**Comment by elrido** [comment]
Brief follow up: Did reword the readme as suggested and can confirm that the tag did now cause a stable tag to be created.

**Comment by Zoey2936** [comment]
> Brief follow up: Did reword the readme as suggested and can confirm that the tag did now cause a stable tag to be created.

But now stable is again the same as latest?

**Comment by Zoey2936** [comment]
See: https://github.com/PrivateBin/docker-nginx-fpm-alpine/commit/7ef0b6e63ef42f3a8d9214e325adc247b61277b1#diff-45dcb68e3db761cd55b88fe04294a52178cf6f80dad4caf16e8fb6935c1fec03

**Comment by elrido** [comment]
Hm, I must have misunderstood the logic behind the final else. I'll undo that part again, back to your change. Sorry. :-(

**Comment by Zoey2936** [comment]
No problem, it does the following:
If edge is true it runs edge build
if the workflow is triggered through a push, then it builds normal and adds stable
and otherwise it runs normals

**Pull request merged**
